import("//arkweb/build/hap/hap.gni")

ohos_hap("ohos_browser_shell") {
  auto_signed = true
  output = "$root_out_dir/ohos_browser_shell.hap"
  deps = [ "//ohos_nweb_ex:browser_service_har" ]

  npm_har = "$root_out_dir/browser_service_hos.tgz"
  if (defined(use_musl) && use_musl) {
    npm_har = "$root_out_dir/browser_service_musl.tgz"
  }

  update_har = [ string_join(
          ":",
          [
            rebase_path(npm_har),
            rebase_path(
                "//ohos_nweb_ex/browser_service/build/default/outputs/default/browser_service.tgz"),
          ]) ]
}
