# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/buildflag_header.gni")
import("//build/config/features.gni")
import("//build/config/ohos/config.gni")
import("//ohos_nweb/src/nweb_sysevent.gni")
import("//tools/grit/grit_rule.gni")
import("//tools/grit/repack.gni")
import("//testing/libfuzzer/fuzzer_test.gni")
import("//testing/test.gni")
import("//arkweb/build/features/features.gni")

fuzzer_test("arkweb_render_process_host_fuzzer") {
  sources = [ "arkweb_render_process_host_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//content/browser:browser",
    "//content/test:test_support",
  ]
}

group("ohos_test") {
    testonly = true
    deps = []
    deps += [
      ":arkweb_render_process_host_fuzzer",
    ]
}