
#
# Extending //gpu:gpu_unittests target
#
gpu_unittests_ext = {
  sources = [ 
    "//arkweb/chromium_ext/gpu/ipc/common/nweb_native_window_tracker_unittest.cc",
    "//arkweb/chromium_ext/content/browser/gpu/ark_web_compositor_util_unittest.cc",
    "//arkweb/chromium_ext/content/gpu/in_process_gpu_thread_utils_unittest.cc",
    "//arkweb/chromium_ext/gpu/command_buffer/common/gpu_memory_buffer_support_utils_unittest.cc",
  ]
  sources_del = [ ]
  deps = [
    "//arkweb/build/features",
    "//content/public/common",
    "//components/subresource_filter/content/browser",
    "//cef:libcef_static",
  ]
}

import("command_buffer/service/arkweb_gpu_command_buffer_service_ext.gni")
import("command_buffer/service/ohos/arkweb_gpu_command_buffer_service_ohos_ext.gni")
import("config/arkweb_gpu_config_ext.gni")
import("ipc/service/arkweb_gpu_ipc_service_ext.gni")
gpu_unittests_ext.sources += arkweb_gpu_command_buffer_service_ohos_sources
gpu_unittests_ext.sources += arkweb_gpu_command_buffer_service_ohos_unittest
gpu_unittests_ext.sources += arkweb_gpu_command_buffer_service_sources
gpu_unittests_ext.sources += arkweb_gpu_command_buffer_service_unittest
gpu_unittests_ext.sources += arkweb_gpu_config_unittest
gpu_unittests_ext.sources += arkweb_gpu_ipc_service_unittest

if (!is_official_build) {
  gpu_unittests_ext.sources_del += [ "ipc/service/gpu_channel_unittest.cc" ]
}