# Copyright 2024 The Huawei Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//arkweb/build/features/features.gni")
arkweb_gpu_vulkan = []

if (arkweb_vulkan) {
arkweb_gpu_vulkan += [
  "//arkweb/chromium_ext/gpu/vulkan/vulkan_image_ohos.cc",
  "//arkweb/chromium_ext/gpu/vulkan/vulkan_surface_ext.h",
]
}
