source_set("network_service") {
  sources = [
    "//arkweb/chromium_ext/services/network/url_loader_utils.h",
    "//arkweb/chromium_ext/services/network/url_loader_utils.cc",
    "//arkweb/chromium_ext/services/network/url_loader_ext.h",
    "//arkweb/chromium_ext/services/network/url_loader_ext.cc",
  ]

  deps = [
    "//net",
    "//base",
  ]
}