_auto_gni_path = "$target_gen_dir/adapter_ndk_config.gni"
_script = "//arkweb/ohos_adapter_ndk/ndk_tools/gen_ndk.py"
import("//build/config/ohos/config.gni")
_args = [
  "--input",
  rebase_path("//arkweb/ohos_adapter_ndk/ndk_tools/adapter_ndk_api.json",
              root_build_dir),
  "--output",
  rebase_path(target_gen_dir, root_build_dir),
  "--absolute",
  target_gen_dir,
  "--version",
  "15",
]

exec_script(_script, _args)

import(_auto_gni_path)

action("adapter_ndk_gen") {
  script = _script
  outputs = stub_sources + wrapper_sources
}

shared_library("adapter_ndk_stub") {
  sources = stub_sources

  deps = [ ":adapter_ndk_gen" ]
}

declare_args() {
  webview_only = true
  webview_print_enable = true
  if (defined(global_parts_info) &&
      !defined(global_parts_info.print_print_fwk)) {
    webview_print_enable = false
  }
}

config("adapter_ndk_config") {
  ldflags = wrapper_ldflags
}

source_set("adapter_ndk_wrapper") {
  sources = wrapper_sources
  sources += [ "ndk_version.cc" ]

  deps = [ ":adapter_ndk_gen" ]
  public_configs = [ ":adapter_ndk_config" ]

  lib_dirs = [ root_build_dir ]
  libs = [ "adapter_ndk_stub" ]
}

component("adapter_ndk") {
  defines = []

  sources = [
    "access_token_adapter/access_token_adapter_impl.cpp",
    "audio_capturer_adapter/audio_capturer_adapter_impl.cpp",
    "audio_capturer_adapter/audio_capturer_adapter_impl.h",
    "battery_mgr_adapter/battery_mgr_client_adapter_impl.cpp",
    "battery_mgr_adapter/battery_mgr_client_adapter_impl.h",
    "cert_mgr_adapter/cert_mgr_adapter_impl.cpp",
    "color_picker_adapter/color_picker_adapter_impl.cpp",
    "color_picker_adapter/color_picker_adapter_impl.h",

    #"hiviewdfx_adapter/hilog_adapter.cpp",
    "datashare_adapter/datashare_adapter_impl.cpp",
    "date_time_format_adapter/date_time_format_adapter_impl.cpp",
    "date_time_format_adapter/date_time_format_adapter_impl.h",
    "display_manager_adapter/native_display_manager_adapter_impl.cpp",
    "display_manager_adapter/native_display_manager_adapter_impl.h",
    "distributeddatamgr_adapter/ohos_web_snapshot_data_base.cpp",
    "drawing_text_adapter/ohos_drawing_text_adapter_impl.cpp",
    "drawing_text_adapter/ohos_drawing_text_adapter_impl.h",
    "graphic_adapter/ashmem_adapter_impl.cpp",
    "graphic_adapter/native_image_adapter_impl.cpp",
    "graphic_adapter/native_image_adapter_impl.h",
    "graphic_adapter/native_window_adapter_impl.cpp",
    "graphic_adapter/native_window_adapter_impl.h",
    "graphic_adapter/vsync_adapter_impl.cpp",
    "graphic_adapter/vsync_adapter_impl.h",
    "graphic_adapter/window_adapter_impl.cpp",
    "graphic_adapter/window_adapter_impl.h",
    "hiviewdfx_adapter/hitrace_adapter_impl.cpp",
    "inputmethodframework_adapter/imf_adapter_impl.cpp",
    "inputmethodframework_adapter/imf_adapter_impl.h",
    "inputmethodframework_adapter/third_party/cJSON/cJSON.c",
    "inputmethodframework_adapter/third_party/cJSON/cJSON.h",
    "keystore_adapter/keystore_adapter_impl.cpp",
    "keystore_adapter/keystore_adapter_impl.h",
    "media_adapter/audio_cenc_info_adapter_impl.cpp",
    "media_adapter/audio_cenc_info_adapter_impl.h",
    "media_adapter/audio_codec_decoder_adapter_impl.cpp",
    "media_adapter/audio_codec_decoder_adapter_impl.h",
    "media_adapter/buffer_info_adapter_impl.cpp",
    "media_adapter/buffer_info_adapter_impl.h",
    "media_adapter/capability_data_adapter_impl.cpp",
    "media_adapter/codec_format_adapter_impl.cpp",
    "media_adapter/codec_format_adapter_impl.h",
    "media_adapter/drm_adapter_impl.cpp",
    "media_adapter/drm_adapter_impl.h",
    "media_adapter/media_codec_decoder_adapter_impl.cpp",
    "media_adapter/media_codec_decoder_adapter_impl.h",
    "media_adapter/media_codec_list_adapter_impl.cpp",
    "media_adapter/ohos_buffer_adapter_impl.cpp",
    "media_adapter/ohos_buffer_adapter_impl.h",
    "media_adapter/video_encoder_adapter_impl.cpp",
    "media_avsession_adapter/media_avsession_adapter_impl.cpp",
    "media_avsession_adapter/media_avsession_adapter_impl.h",
    "multimodalinputnew_adapter/mmi_new_adapter_impl.cpp",
    "multimodalinputnew_adapter/mmi_new_adapter_impl.h",
    "ndk_callback_wrapper/callback_shared_wrapper.h",
    "net_config_adapter/net_config_adapter_impl.cpp",
    "net_config_adapter/net_config_adapter_impl.h",
    "net_connect_adapter/net_capabilities_adapter_impl.cpp",
    "net_connect_adapter/net_capabilities_adapter_impl.h",
    "net_connect_adapter/net_connect_adapter_impl.cpp",
    "net_connect_adapter/net_connect_adapter_impl.h",
    "net_connect_adapter/net_connect_utils.cpp",
    "net_connect_adapter/net_connect_utils.h",
    "net_connect_adapter/net_connection_properties_adapter_impl.cpp",
    "net_connect_adapter/net_connection_properties_adapter_impl.h",
    "net_event_adapter/net_event_adapter_impl.cpp",
    "net_event_adapter/net_event_adapter_impl.h",
    "net_proxy_adapter_impl/net_proxy_adapter_impl.cpp",
    "net_proxy_adapter_impl/net_proxy_adapter_impl.h",
    "ohos_adapter_helper_decouple.cpp",
    "ohos_adapter_helper_ext.h",
    "ohos_image_adapter/ohos_image_decoder_adapter_impl.cpp",
    "ohos_image_adapter/ohos_image_decoder_adapter_impl.h",
    "ohos_image_adapter/ohos_image_encoder_adapter.cpp",
    "ohos_image_adapter/ohos_image_encoder_adapter.h",
    "ohos_native_buffer_adapter/ohos_native_buffer_adapter_impl.cpp",
    "ohos_native_buffer_adapter/ohos_native_buffer_adapter_impl.h",
    "pasteboard_adapter/src/pasteboard_client_adapter_impl.cpp",
    "pasteboard_adapter/src/pasteboard_client_adapter_utils.cpp",
    "screen_capture_adapter/screen_capture_adapter_impl.cpp",
    "screen_capture_adapter/screen_capture_adapter_impl.h",
    "sensor_adapter/sensor_adapter_impl.cpp",
    "sensor_adapter/sensor_adapter_impl.h",
    "utils/src/ashmem.cpp",
    "window_manager_adapter/window_manager_adapter_impl.cpp",
    "window_manager_adapter/window_manager_adapter_impl.h",
  ]

  include_dirs = [
    "//third_party/ohos_ndk/includes/ohos_adapter",
    "//third_party/jsoncpp/source/include",
    "//arkweb/glue",
    "media_adapter/include",
    "utils/include/",
    "interfaces/",
    "graphic_adapter/",
    "third_party/bounds_checking_function/include",
    "${ohos_sysroot}usr/include/",
    "//third_party/skia",
  ]

  if (target_cpu == "arm" || target_cpu == "arm64" || target_cpu == "x86_64") {
    include_dirs += [ "${ohos_sysroot}usr/include/bundle" ]
  }

  if (target_cpu == "arm64") {
    libs = [
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libffrt.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libhilog_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohinputmethod.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libbundle_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohavsession.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohfileuri.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_image.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_buffer.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_window.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnet_ssl.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohaudio.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_avscreen_capture.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_media_codecbase.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libability_runtime.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_rdb_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libability_access_control.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohinput.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libpasteboard.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libpixelmap.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libpixelmap_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libudmf.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_display_manager.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_window_manager.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libdeviceinfo_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libavplayer.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_media_core.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libace_napi.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libdeviceinfo_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_display_manager.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohpreferences.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libability_runtime.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohsensor.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohbattery_info.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohcommonevent.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_drm.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_media_vdec.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_media_codecbase.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_buffer.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_media_core.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_window.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_media_acodec.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_media_avcencinfo.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libimage_packer.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_color_space_manager.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libimage_source.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libhuks_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libasset_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libtime_service_ndk.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnet_connection.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libtelephony_data.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libtelephony_radio.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libohcommonevent.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_media_venc.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libhitrace_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_vsync.so",
    ]
  } else if (target_cpu == "arm") {
    libs = [
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libffrt.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libhilog_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohinputmethod.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libbundle_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohavsession.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohfileuri.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_image.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_buffer.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_window.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnet_ssl.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohaudio.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_avscreen_capture.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_media_codecbase.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libability_runtime.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_rdb_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libability_access_control.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohinput.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libpasteboard.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libpixelmap.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libpixelmap_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libudmf.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_display_manager.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_window_manager.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libdeviceinfo_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libavplayer.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_media_core.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libace_napi.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libdeviceinfo_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_display_manager.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohpreferences.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libability_runtime.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohsensor.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohbattery_info.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohcommonevent.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_drm.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_media_vdec.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_media_codecbase.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_buffer.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_media_core.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_window.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_media_acodec.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_media_avcencinfo.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libimage_packer.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_color_space_manager.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libimage_source.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libhuks_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libasset_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libtime_service_ndk.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnet_connection.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libtelephony_data.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libtelephony_radio.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libohcommonevent.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_media_venc.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libhitrace_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_vsync.so",
    ]
  } else if (target_cpu == "x86_64" || target_cpu == "x64") {
    libs = [
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libffrt.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libhilog_ndk.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohinputmethod.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libbundle_ndk.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohavsession.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohfileuri.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_image.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_buffer.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_window.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnet_ssl.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohaudio.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_avscreen_capture.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_media_codecbase.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libability_runtime.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_rdb_ndk.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libability_access_control.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohinput.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libpasteboard.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libpixelmap.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libpixelmap_ndk.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libudmf.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_display_manager.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_window_manager.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libdeviceinfo_ndk.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libavplayer.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_media_core.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libace_napi.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libdeviceinfo_ndk.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_display_manager.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohpreferences.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libability_runtime.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohsensor.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohbattery_info.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohcommonevent.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_drm.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_media_vdec.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_media_codecbase.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_buffer.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_media_core.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_window.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_media_acodec.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_media_avcencinfo.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libimage_packer.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_color_space_manager.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libimage_source.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libhuks_ndk.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libasset_ndk.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libtime_service_ndk.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnet_connection.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libtelephony_data.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libtelephony_radio.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libohcommonevent.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_media_venc.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libhitrace_ndk.z.so",
    ]
  }

  if (target_cpu == "arm") {
    libs += [
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libbundle_ndk.z.so",
      "${ohos_sysroot}usr/lib/arm-linux-ohos/libnative_drawing.so",
    ]
  } else if (target_cpu == "arm64") {
    libs += [
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libbundle_ndk.z.so",
      "${ohos_sysroot}usr/lib/aarch64-linux-ohos/libnative_drawing.so",
    ]
  } else if (target_cpu == "x86_64" || target_cpu == "x64") {
    libs += [
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libbundle_ndk.z.so",
      "${ohos_sysroot}usr/lib/x86_64-linux-ohos/libnative_drawing.so",
    ]
  }

  if (webview_only) {
    defines += [ "WEBVIEWK_ONLY" ]
  }

  if (webview_print_enable) {
    defines += [ "NWEB_PRINT_ENABLE" ]
  }

  import("//build/config/sanitizers/sanitizers.gni")
  if (use_fuzzing_engine) {
    defines += [ "USE_LIBFUZZER" ]
  }

  deps = [
    "//arkweb/build/features",
    "//base:tracing_buildflags",
    "//base/allocator/partition_allocator:raw_ptr",
    "//third_party:huawei_securec",
    "//third_party/boringssl",
  ]
  if (defined(is_arkweb) && is_arkweb) {
    deps += [ "//arkweb/build/features:features" ]
  }
}
