// Copyright 2017 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

namespace url_pattern_index.flat;

// NOTE: Increment url_pattern_index::kUrlPatternIndexFormatVersion whenever
// making a breaking change to this schema.

enum CssPatternType : ubyte {
  SUBSTRING,
}

enum CssOptionFlag : ubyte (bit_flags) {
  IS_WHITELIST,
  IS_CASE_INSENSITIVE,
}

// The flat representation of a single URL rule. For more details regarding the
// fields please see the comments to url_pattern_index::proto::UrlRule.
table CssRule {
  // Rule matching options, a bitmask consisting of OptionFlags.
  options : ubyte;
  // css_pattern_type : CssPatternType = SUBSTRING
  // The list of domains to be included/excluded from the filter's affected set.
  // Should either be null or have at least a single element. The domains
  // should be in lower-case and kept sorted as defined by
  // url_pattern_index::CompareDomains. The entries must consist of only ascii
  // characters. Use punycode encoding for internationalized domains.
  domains_included : [string];
  domains_excluded : [string];

  css_selector : string;
  // An id which uniquely identifies the rule. Clients must ensure uniqueness if
  // they use this field.
  id : uint;

  // Priority of the rule. Larger the value, greater the priority.
  priority : uint;
}

// Contains an N-gram (acting as a key in a hash table) and a list of URL rules
// associated with that N-gram.
table NGramToCssRules {
  // A string consisting of N (up to 8) ascii-only non-special characters, which
  // are stored in the lowest N non-zero bytes, lower bytes corresponding to
  // later symbols. These are lower-cased to support case-insensitive matching.
  ngram : ulong;

  // The list of rules containing |ngram| as a substring of their URL pattern.
  // Sorted in descending order of rule priority.
  rule_list : [CssRule];
}

// A data structure used to select only a handful of URL rule candidates that
// need to be matched against a certain resource URL.
table CssPatternIndex {
  // The N of an N-gram index. Note: |n| should be between 1 and 8.
  n : uint;

  // A hash table with open addressing. The keys of the table are N-grams.
  ngram_index : [NGramToCssRules];

  // The slot that is pointed to by all empty slots of Ingram index| hash table.
  // Note: This is a workaround needed because null offsets are not allowed as
  // elements of FlatBuffer arrays.
  ngram_index_empty_slot : NGramToCssRules;

  // A list storing the rules that doesn't contain any valid N-grams in their
  // URL patterns. Contains all the REGEXP rules as well. Sorted in descending
  // order of rule priority.
  // TODO(pkalinnikov): Think about better implementation for the fallback
  // index. Possibly mak it a hash map and maybe merge it with the N-gram
  // index, since we can treat any sequence of characters shorter than N as an
  // N-gram with zero bytes used for padding.
  fallback_rules : [CssRule];

  // A list storing the css rules that doesn't have domain
  // Element hiding needs to use frame url for domain matching,
  // so we choose domain as the N-gram keyword, and the selector will not be used
  // as a quick query condition, so there is no need to use Hash table and Ngram
  // algorithm.
  no_domain_rules : [CssRule];
}

root_type CssPatternIndex;
