import("//arkweb/build/features/features.gni")
import("//build/config/ohos/config.gni")
arkweb_ui_gl_ext_sources = [
  "buffer_format_utils.cc",
  "buffer_format_utils.h",
  "//arkweb/chromium_ext/ui/gl/gl_surface_egl_ohos.cc",
  "//arkweb/chromium_ext/ui/gl/ohos/ohos_native_image.cc",
  "//arkweb/chromium_ext/ui/gl/ohos/native_buffer_utils.cc",
  "//arkweb/chromium_ext/ui/gl/ohos/frame_available_listener_impl.cc",
  "//arkweb/chromium_ext/ui/gl/arkweb_gl_surface_egl_utils.h",
  "//arkweb/chromium_ext/ui/gl/arkweb_gl_surface_egl_utils.cc",
]

include_dirs = [ "//third_party/mesa_headers" ]

#all_dependent_configs = [ ":gl_config" ]

public_configs = [ "//third_party/khronos:khronos_headers" ]

arkweb_ui_gl_ext_deps = [
  "//ohos_glue:ohos_adapter_glue_source",
]

if (arkweb_same_layer) {
  arkweb_ui_gl_ext_sources += [
    "android/egl_fence_utils.cc",
    "android/egl_fence_utils.h",
    "gl_fence_android_native_fence_sync.cc",
    "gl_fence_android_native_fence_sync.h",
  ]
  arkweb_ui_gl_ext_deps += [ "//third_party/libsync" ]
}
