arkweb_unittests_deps = [
  "//content/public/common",
]

arkweb_unittests_sources = [
  "//content/browser/browser_thread_impl.cc",
  "//content/browser/scheduler/browser_task_executor.cc",
  "//content/browser/scheduler/browser_io_thread_delegate.cc",
  "//content/browser/scheduler/browser_task_queues.cc",
  "//content/browser/scheduler/browser_ui_thread_scheduler.cc",
  "//content/browser/scheduler/browser_task_priority.cc",
  "//arkweb/chromium_ext/content/renderer/render_remote_proxy_ohos.cc",
  "//arkweb/chromium_ext/content/renderer/render_remote_proxy_ohos.h",
  "//arkweb/chromium_ext/ui/gl/arkweb_gl_surface_egl_utils_unittest.cc",
  "//arkweb/chromium_ext/ui/gl/gl_surface_egl_ohos_unittest.cc",
  "//arkweb/ohos_nweb/src/sysevent/event_reporter.h",
  "//arkweb/ohos_nweb/src/sysevent/event_reporter.cc",
  "//arkweb/chromium_ext/ui/gl/ohos/native_buffer_utils_unittest.cc",
  "//arkweb/chromium_ext/ui/gl/ohos/ohos_native_image_unittest.cc",
]