# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//testing/test.gni")
import("//arkweb/build/features/features.gni")

test("ohos_nweb_unittests") {
  configs += []

  include_dirs = [ "//ppapi/lib/gl/include" ]

  sources = [
    "ohos_nweb_test_suite.cc",
    "ohos_nweb_test_suite.h",
    "run_all_unittests.cc",
  ]

  public_deps = [
    "//testing/gmock",
    "//testing/gtest",
  ]

  deps = [
    "//ohos_nweb:unittests",
    "//base",
    "//base/test:test_support",
    "//third_party/boringssl",
    "//ohos_glue:ohos_nweb_glue_source",
    "//ohos_glue:ohos_adapter_glue_source",
    "//third_party/boringssl",
    "//content/public/common",
  ]

  if (enable_arkweb_ext) {
    deps += [ "//ohos_nweb_ex/test:ohos_nweb_ex_unittests", ]
  }

  if (arkweb_unittests) {
    configs += [
      "//arkweb/chromium_ext:ohos_nweb_unittests_config",
    ]
  }
}
