if (is_arkweb){
  import("//arkweb/build/features/features.gni")
}

arkweb_media_base_ohos_sources = [
  "//arkweb/chromium_ext/media/base/ohos/ohos_media_codec_bridge.h",
  "//arkweb/chromium_ext/media/base/ohos/ohos_media_decoder_bridge_impl.cc",
  "//arkweb/chromium_ext/media/base/ohos/ohos_media_decoder_bridge_impl.h",

  "//arkweb/chromium_ext/media/base/ohos/ohos_media_codec_util.cc",
  "//arkweb/chromium_ext/media/base/ohos/ohos_media_codec_util.h",

  "//arkweb/chromium_ext/media/base/ohos/ohos_media_player_bridge.cc",
  "//arkweb/chromium_ext/media/base/ohos/ohos_media_player_bridge.h",

  "//arkweb/chromium_ext/media/base/ohos/ohos_media_player_callback.cc",
  "//arkweb/chromium_ext/media/base/ohos/ohos_media_player_callback.h",

  "//arkweb/chromium_ext/media/base/ohos/ohos_media_player_listener.cc",
  "//arkweb/chromium_ext/media/base/ohos/ohos_media_player_listener.h",

  "//arkweb/chromium_ext/media/base/ohos/buffer_flush_config_adapter_impl.cc",
  "//arkweb/chromium_ext/media/base/ohos/buffer_flush_config_adapter_impl.h",

  "//arkweb/chromium_ext/media/base/ohos/buffer_request_config_adapter_impl.cc",
  "//arkweb/chromium_ext/media/base/ohos/buffer_request_config_adapter_impl.h",

  "//arkweb/chromium_ext/media/base/ohos/codec_config_para_adapter_impl.cc",
  "//arkweb/chromium_ext/media/base/ohos/codec_config_para_adapter_impl.h",

  "//arkweb/chromium_ext/media/base/ohos/decoder_format_adapter_impl.cc",
  "//arkweb/chromium_ext/media/base/ohos/decoder_format_adapter_impl.h",

  "//arkweb/chromium_ext/media/base/ohos/ohos_media_codec_bridge_impl.cc",
  "//arkweb/chromium_ext/media/base/ohos/ohos_media_codec_bridge_impl.h",

  "//arkweb/chromium_ext/media/base/ohos/ohos_media_resource_getter.cc",
  "//arkweb/chromium_ext/media/base/ohos/ohos_media_resource_getter.h",
]

if (arkweb_enable_cdm) {
  arkweb_media_base_ohos_sources += [
    "//arkweb/chromium_ext/media/base/ohos/ohos_cdm_factory.cc",
    "//arkweb/chromium_ext/media/base/ohos/ohos_cdm_factory.h",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_crypto_context_impl.cc",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_crypto_context_impl.h",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_crypto_context.h",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_bridge_client.cc",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_bridge_client.h",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_bridge_delegate.cc",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_bridge_delegate.h",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_bridge_factory.cc",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_bridge_factory.h",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_bridge.cc",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_bridge.h",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_storage_bridge.cc",
    "//arkweb/chromium_ext/media/base/ohos/ohos_media_drm_storage_bridge.h",
  ]
}