# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/buildflag_header.gni")

source_set("prp_preload") {
  visibility = [
    "//services/network:network_service",
    "//services/network:tests",
    "//arkweb/chromium_ext/services/network/prp_preload/tests:prp_preload_unittests",
  ]

  include_dirs = [
    "//arkweb/chromium_ext/services/network/prp_preload/include",
    "//arkweb/chromium_ext/services/network/prp_preload/include/preload_runner",
  ]

  deps = [
    "//base",
    "//net/third_party/quiche",
    "//services/network/public/mojom",
  ]

  if (target_cpu == "arm64") {
    defines = [ "WEBVIEW_ARM64" ]
  }

  sources = [
    "src/disk_cache_backend_factory.cc",
    "src/disk_cache_file.cc",
    "src/disk_cache_info_parser.cc",
    "src/page_res_parallel_preload_mgr_impl.cc",
    "src/preload_runner/preconnect_runner.cc",
    "src/preload_runner/prpp_request_loader_factory_impl.cc",
    "src/preload_runner/prpp_request_loader_impl.cc",
    "src/res_parallel_preload_ctrler.cc",
    "src/res_preload_scheduler.cc",
    "src/res_request_info_cache_mgr.cc",
    "src/res_request_info_updater.cc",
  ]
}