#
# Extending //headless:headless_unittests target
#
headless_unittests_ext = {
  sources = ["//arkweb/chromium_ext/ui/ozone/platform/headless/headless_screen_ohos_unittest.cc"]
  deps = [
    "//base",
    "//base/test:test_support",
    "//build:chromeos_buildflags",
    "//skia",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base",
    "//ui/base:features",
    "//ui/base/dragdrop:types",
    "//ui/display:test_support",
    "//ui/events:test_support",
    "//ui/ozone:platform",
    "//ui/ozone:test_support",
  ]
}