arkweb_media_audio_ohos_sources = [
    "//arkweb/chromium_ext/media/audio/ohos/audio_capturer_options_adapter_impl.cc",
    "//arkweb/chromium_ext/media/audio/ohos/audio_capturer_options_adapter_impl.h",

    "//arkweb/chromium_ext/media/audio/ohos/audio_dump.cc",
    "//arkweb/chromium_ext/media/audio/ohos/audio_dump.h",

    "//arkweb/chromium_ext/media/audio/ohos/buffer_desc_adapter_impl.cc",
    "//arkweb/chromium_ext/media/audio/ohos/buffer_desc_adapter_impl.h",

    "//arkweb/chromium_ext/media/audio/ohos/ohos_audio_capturer_source.cc",
    "//arkweb/chromium_ext/media/audio/ohos/ohos_audio_capturer_source.h",

    "//arkweb/chromium_ext/media/audio/ohos/ohos_audio_manager.cc",
    "//arkweb/chromium_ext/media/audio/ohos/ohos_audio_manager.h",
]