arkweb_content_browser_media_ohos_player_sources = [
    "//arkweb/chromium_ext/content/browser/media/ohos/ohos_custom_media_player_renderer.cc",
    "//arkweb/chromium_ext/content/browser/media/ohos/ohos_custom_media_player_renderer.h",
]

arkweb_content_browser_media_ohos_audio_sources = [
    "//arkweb/chromium_ext/content/browser/media/ohos/ohos_media_player_renderer_web_contents_observer.cc",
    "//arkweb/chromium_ext/content/browser/media/ohos/ohos_media_player_renderer_web_contents_observer.h",
]