import("//arkweb/build/features/features.gni")

arkweb_media_mojo_services_sources = [
    "//arkweb/chromium_ext/media/mojo/services/gpu_mojo_media_client_ohos.cc",
]

if (arkweb_enable_cdm) {
  arkweb_media_mojo_services_sources += [
    "//arkweb/chromium_ext/media/mojo/services/ohos_mojo_media_client.cc",
    "//arkweb/chromium_ext/media/mojo/services/ohos_mojo_media_client.h",
    "//arkweb/chromium_ext/media/mojo/services/ohos_mojo_util.cc",
    "//arkweb/chromium_ext/media/mojo/services/ohos_mojo_util.h",
  ]
}