# Copyright (c) 2025 Huawei Device Co., Ltd. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

arkweb_ui_views_extension_sources = get_path_info([
    "extension_install_prompt_ext.cc",
    "extension_install_prompt_ext.h",
    "extension_multiple_uninstall_dialog_ohos.cc",
    "extension_multiple_uninstall_dialog_ohos.h",
    "extension_uninstall_dialog_ohos.cc",
    "extension_uninstall_dialog_ohos.h",
  ], "abspath")
