import("//arkweb/build/features/features.gni")

arkweb_base_ext_sources = []

arkweb_base_ext_sources += [
  "//arkweb/chromium_ext/base/message_loop/message_pump_ohos.cc",
  "//base/profiler/stack_sampler_android.cc",
  "//arkweb/chromium_ext/base/ohos/sys_info_utils_ext.cc",
  "//arkweb/chromium_ext/base/ohos/sys_info_utils_ext.h",
  "//arkweb/chromium_ext/base/ohos/dynamic_frame_loss_monitor.cc",
  "//arkweb/chromium_ext/base/ohos/dynamic_frame_loss_monitor.h",
  "//arkweb/chromium_ext/base/files/memory_mapped_file_ext.cc",
  "//arkweb/chromium_ext/base/files/memory_mapped_file_ext.h",
  "//arkweb/chromium_ext/base/ohos/blankless/blankless_controller.cc",
  "//arkweb/chromium_ext/base/ohos/blankless/blankless_controller.h",
  "//arkweb/chromium_ext/base/ohos/nweb_engine_event_logger.cc",
  "//arkweb/chromium_ext/base/ohos/nweb_engine_event_logger.h",
  "//arkweb/chromium_ext/base/ohos/nweb_engine_event_logger_code.cc",
  "//arkweb/chromium_ext/base/ohos/nweb_engine_event_logger_code.h",
]

if (arkweb_file_upload) {
  arkweb_base_ext_sources += [
    "//arkweb/chromium_ext/base/datashare_uri_utils.cc",
    "//arkweb/chromium_ext/base/datashare_uri_utils.h",
    "//arkweb/chromium_ext/base/report_loss_frame_ext.cc",
    "//arkweb/chromium_ext/base/report_loss_frame_ext.h",
  ]
}

if (arkweb_i18n) {
  arkweb_base_ext_sources += [
    "//arkweb/chromium_ext/base/ohos/locale_utils.cc",
    "//arkweb/chromium_ext/base/ohos/locale_utils.h",
  ] 
}

if (arkweb_vulkan) {
  arkweb_base_ext_sources += [
    "//arkweb/chromium_ext/base/ohos/scoped_native_buffer_handle.cc",
    "//arkweb/chromium_ext/base/ohos/scoped_native_buffer_handle.h",
  ]
}

if (defined(arkweb_logger_report) && arkweb_logger_report) {
  arkweb_base_ext_sources += [
    "//arkweb/chromium_ext/base/ohos/logger.cc",
    "//arkweb/chromium_ext/base/ohos/logger.h",
  ]
}

if (arkweb_crashpad) {
  arkweb_base_ext_sources += [
    "//arkweb/chromium_ext/base/task/task_queue_impl_ext.cc",
    "//arkweb/chromium_ext/base/task/task_queue_impl_ext.h",
  ]
}

arkweb_metrics_sources = [
  "//arkweb/chromium_ext/base/metrics/field_trial_utils.cc",
  "//arkweb/chromium_ext/base/metrics/field_trial_utils.h",
]

arkweb_metrics_unittests_sources = [
  "//arkweb/chromium_ext/base/metrics/field_trial_utils_unittest.cc",
]

arkweb_base_ohos_ltpo_sources = [
  "//arkweb/chromium_ext/base/ohos/ltpo/src/dynamic_frame_rate_decision.cc",
  "//arkweb/chromium_ext/base/ohos/ltpo/include/dynamic_frame_rate_decision.h",
  "//arkweb/chromium_ext/base/ohos/ltpo/src/sliding_observer.cc",
  "//arkweb/chromium_ext/base/ohos/ltpo/include/sliding_observer.h",
  "//arkweb/chromium_ext/base/ohos/ltpo/include/ltpo_strategy.h",
  "//arkweb/chromium_ext/base/ohos/ltpo/src/touch_observer.cc",
  "//arkweb/chromium_ext/base/ohos/ltpo/include/touch_observer.h",
]

#TODO
arkweb_base_ohos_ltpo_unittests_sources = [
  "//arkweb/chromium_ext/base/ohos/ltpo/src/dynamic_frame_rate_decision_unittest.cc",
  "//arkweb/chromium_ext/base/ohos/ltpo/src/sliding_observer_unittest.cc",
]

arkweb_base_ohos_d_vsync_sources = [
  "//arkweb/chromium_ext/base/ohos/d_vsync/src/d_vsync_controller.cc",
  "//arkweb/chromium_ext/base/ohos/d_vsync/include/d_vsync_controller.h",
]

arkweb_base_i18n_sources = [
  "//arkweb/chromium_ext/base/i18n/icu_util_ohos.h",
]

arkweb_base_process_ext_sources = [
  "//arkweb/chromium_ext/base/process/process_handle_posix_ex.cc",
  "//arkweb/chromium_ext/base/process/process_handle_posix_ex.h",
]