# Copyright (c) 2024 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/buildflag_header.gni")
import("//build/config/features.gni")
import("//build/config/ohos/config.gni")
import("//ohos_nweb/src/nweb_sysevent.gni")
import("//tools/grit/grit_rule.gni")
import("//tools/grit/repack.gni")
import("//testing/libfuzzer/fuzzer_test.gni")
import("//testing/test.gni")
import("//arkweb/build/features/features.gni")


## add ohos fuzz test case here
group("nweb_cookie_manager_imp_fuzzers") {
  testonly = true
  deps = [
    "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/nweb_cookie_manager/",
  ]
}

group("ohos_fuzz") {
    testonly = true
    deps = [
      ":nweb_cookie_manager_imp_fuzzers",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/date_time_format_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/graphic_adapter/ashmem_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/graphic_adapter/window_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/graphic_adapter/native_image_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/graphic_adapter/native_window_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/graphic_adapter/vsync_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/ohos_native_buffer_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/color_picker_adapter:color_picker_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/pasteboard_adapter:pasteboard_client_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/utils:ashmem_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/data_base_adapter_impl_fuzzer:data_base_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/permission_data_base_adapter_fuzzer:permission_data_base_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/nweb_inputmethod_fuzzer:nweb_inputmethod_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/nweb_imf_cursor_info_adapter_fuzzer:nweb_imf_cursor_info_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/cef_delegate/nweb_access_request_delegate_fuzzer:nweb_access_request_delegate_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/cef_delegate/nweb_extension_content_settings_cef_delegate_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/inputmethodframework_adapter:nweb_imf_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/multimodalinputnew_adapter:mmi_new_adapter_impl_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/battery_mgr_adapter:battery_mgr_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/datashare_adapter:datashare_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/distributeddatamgr_adapter/ohos_web_snapshot_data_base:ohos_web_snapshot_data_base_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/event_handler_adapter:event_handler_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/location_adapter:location_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/print_manager_adapter:print_manager_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/sensor_adapter:sensor_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/content/browser/renderer_host/arkweb_render_process_host_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/cert_mgr_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/net_proxy_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/net_connect_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/net_config_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/keystore_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/cef_delegate/nweb_devtools_message_handler_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/arkweb_scheme_handler",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/nweb_storage_impl_other_fuzzer:nweb_storage_impl_other_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/nweb_data_base_impl_secondary_fuzzer:nweb_data_base_impl_secondary_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/hiviewdfx_adapter/hilog_adapter_fuzzer:hilog_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/hiviewdfx_adapter/hitrace_adapter_fuzzer:hitrace_adapter_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_nweb/src/capi_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/chromium_ext/components/download/internal/common/arkweb_download_file_impl_ext_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/ohos_adapter_ndk_ai_fuzzer:ohos_adapter_ndk_api01_fuzzer",
      "//arkweb/chromium_ext/ohos_test/fuzztest/ohos_adapter_ndk/ohos_adapter_ndk_ai_fuzzer:ohos_adapter_ndk_api02_fuzzer",
    ]
}

fuzzer_test("nweb_impl_fuzzer") {
  sources = [
    "fuzztest/ohos_nweb/src/nweb_impl_fuzzer.cc",
  ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//ohos_nweb/src/cef_delegate",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_impl_createweb") {
  sources = [
    "fuzztest/nweb_impl_createweb_fuzzer.cc",
  ]
  defines = [
    "OHOS_CLOUD_CONTROL",
  ]
  include_dirs = [
    "//cef",
    "//ios/chrome/browser/application_context",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_impl_render_main") {
  sources = [
    "fuzztest/nweb_render_main_fuzzer.cc",
  ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_resource_handle_fuzzer") {
  sources = [
    "fuzztest/ohos_nweb/src/cef_delegate/nweb_resource_handle_fuzzer.cc",
  ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//base",
    "//net",
    "//ui/base",
    "//cef:libcef_static",
    "//components/embedder_support:browser_util",
    "//ohos_nweb_ex/overrides/cef:cef",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
  ]
}

## add chromium fuzz test case here
group("chromium_fuzz") {
    testonly = true
    deps = [
        "//base:base64_decode_fuzzer",
    ]
}

## add ohos unit test case here
group("ohos_unittest") {
    testonly = true
    deps = [
        
    ]
}

## add chromium unit test case here
group("chromium_unittest") {
    testonly = true
    deps = [
        
    ]
}

group("ohos_test") {
    testonly = true
    deps = [
        ":ohos_fuzz",
        ":chromium_fuzz",
        ":ohos_unittest",
        ":chromium_unittest",
    ]
}

####################################

fuzzer_test("native_loader_fuzzer") {
  sources = [
    "fuzztest/native_loader_fuzzer.cc",
  ]
  include_dirs = [
    "//third_party/blink",
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//content/public/common",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}
 
fuzzer_test("html_plugin_element_fuzzer") {
  sources = [
    "fuzztest/html_plugin_element_fuzzer.cc",
  ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//content/public/common",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

####################################

fuzzer_test("clipboard_fuzzer") {
  sources =
      [ "fuzztest/content/browser/renderer_host/clipboard_host_fuzzer.cc" ]
  deps = [
    "//base",
    "//content/browser",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
  ]
  include_dirs = [
    "//cef",
    "//content/browser/renderer_host",
    "//ui/base/clipboard",
    "//content/public/browser",
  ]
}

fuzzer_test("arkweb_child_process_launcher_helper_utils_fuzzer") {
  sources = [ "fuzztest/content/browser/arkweb_child_process_launcher_helper_utils_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//content/test:test_support",
  ]
}

fuzzer_test("nweb_accessibility_node_info_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/cef_delegate/nweb_accessibility_node_info_impl_fuzzer.cc" ]
  include_dirs = [
    "//arkweb/ohos_nweb/src/cef_delegate",
    "//ohos_nweb/include",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("input_event_ohos_fuzzer") {
  sources = [ "fuzztest/third_party/blink/common/event/input_event_ohos_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("gesture_detector_utils_fuzzer") {
  sources = [ "fuzztest/ui/events/gesture_detection/gesture_detector_utils_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("gesture_detector_ext_fuzzer") {
  sources = [ "fuzztest/ui/events/gesture_detection/gesture_detector_ext_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_delegate_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/cef_delegate/nweb_delegate_fuzzer.cc" ]
  include_dirs = [
    "//arkweb/ohos_adapter_ndk/interfaces",
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_context_menu_params_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_context_menu_params_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_cursor_info_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_cursor_info_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_custom_keyboard_handler_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_custom_keyboard_handler_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_date_time_chooser_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_date_time_chooser_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_key_event_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_key_event_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_event_handler_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_event_handler_fuzzer.cc" ]
  include_dirs = [
    "//arkweb/ohos_adapter_ndk/interfaces",
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_find_delegate_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_find_delegate_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_input_handler_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/nweb_input_handler_fuzzer.cc" ]
  include_dirs = [
    "//arkweb/ohos_adapter_ndk/interfaces",
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_touch_handle_hot_zone_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_touch_handle_hot_zone_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_touch_handle_state_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_touch_handle_state_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_select_menu_bound_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_select_menu_bound_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_select_popup_menu_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_select_popup_menu_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_file_selector_params_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_file_selector_params_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("audio_capturer_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/media_adapter/audio_capturer_adapter_impl_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/audio_capturer_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("screen_capture_adapter_impl_fuzzer") {
  sources = [
    "arkweb/ohos_adapter_ndk/interfaces/screen_capture_adapter.h",
    "fuzztest/ohos_adapter_ndk/screen_capture_adapter/screen_capture_adapter_impl_fuzzer.cpp"
  ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/screen_capture_adapter",
    "//arkweb/ohos_adapter_ndk/interfaces",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("video_encoder_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/media_adapter/video_encoder_adapter_impl_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("media_avsession_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/media_avsession_adapter/media_avsession_adapter_impl_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_avsession_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("media_codec_decoder_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/media_adapter/media_codec_decoder_adapter_impl_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("media_codec_list_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/media_adapter/media_codec_list_adapter_impl_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("drm_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/media_adapter/drm_adapter_impl_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("ohos_buffer_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/media_adapter/ohos_buffer_adapter_impl_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//arkweb/ohos_adapter_ndk/media_adapter/include",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("nweb_preference_delegate_secondary_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/cef_delegate/nweb_preference_delegate_secondary_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_first_meaningful_paint_details_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/nweb_first_meaningful_paint_details_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_largest_contentful_paint_details_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/nweb_largest_contentful_paint_details_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_output_handler_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/nweb_output_handler_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("event_report_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/event_report/event_report_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("native_display_manager_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/display_manager_adapter/native_display_manager_adapter_impl_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/display_manager_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("ohos_drawing_text_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/drawing_text_adapter/ohos_drawing_text_adapter_impl_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/drawing_text_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("first_meaningful_paint_details_fuzzer") {
  sources = [ "fuzztest/cef/ohos_cef_ext/libcef/browser/first_meaningful_paint_details_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("largest_contentful_paint_details_fuzzer") {
  sources = [ "fuzztest/cef/ohos_cef_ext/libcef/browser/largest_contentful_paint_details_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("render_process_state_handler_fuzzer") {
  sources = [ "fuzztest/cef/ohos_cef_ext/libcef/browser/alloy/render_process_state_handler_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("alloy_native_embed_first_frame_paint_event_fuzzer") {
  sources = [ "fuzztest/cef/ohos_cef_ext/libcef/browser/web_client_extension/alloy_native_embed_first_frame_paint_event_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("audio_cenc_info_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/media_adapter/audio_cenc_info_adapter_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("audio_codec_decoder_adapter_impl_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/media_adapter/audio_codec_decoder_adapter_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("ohos_image_decoder_adapter_fuzzer") {
  sources = [ "fuzztest/ohos_adapter_ndk/ohos_image_decoder_adapter_fuzzer/ohos_image_decoder_adapter_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("nweb_media_info_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/native_media_player/nweb_media_info_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//ohos_nweb/src/native_media_player",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("nweb_native_media_player_handler_impl_fuzzer") {
  sources = [ "fuzztest/ohos_nweb/src/native_media_player/nweb_native_media_player_handler_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//ohos_nweb/src/native_media_player",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("html_embed_element_for_include_fuzzer") {
  sources = [ "fuzztest/third_party/blink/renderer/core/html/html_embed_element_for_include_fuzzer.cpp" ]
  include_dirs = [
    "//cef",
    "//ohos_nweb/include",
    "//ohos_nweb/src",
    "//v8/include",
    "//third_party/blink",
  ]
  deps = [
    "//arkweb/ohos_adapter_ndk:adapter_ndk_stub",
    "//cef:libcef_static",
    "//ohos_nweb:cef_nweb",
    "//ohos_nweb:nweb_sources",
  ]
}

fuzzer_test("ohos_media_codec_bridge_impl_fuzzer") {
  sources = [ "fuzztest/media/base/ohos/ohos_media_codec_bridge_impl_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
    "//arkweb/chromium_ext/media/base/ohos",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}

fuzzer_test("ohos_heif_image_decode_fuzzer") {
  sources = [ "fuzztest/media/base/gpu/ohos_heif_image_decode_fuzzer.cc" ]
  include_dirs = [
    "//cef",
    "//cef/include",
    "//ohos_nweb/include",
    "//arkweb/ohos_adapter_ndk/media_adapter",
    "//third_party/ohos_ndk/includes/ohos_adapter",
    "//arkweb/chromium_ext/media/base/ohos",
  ]
  deps = [
    "//cef:libcef_static",
    "//ohos_nweb:nweb_sources",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gmock",
    "//arkweb/ohos_adapter_ndk:adapter_ndk",
  ]
}