# Copyright (c) 2022 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//arkweb/build/features/features.gni")
import("//build/buildflag_header.gni")
import("//build/config/features.gni")
import("//build/config/ohos/config.gni")
import("//cef/libcef/features/features.gni")
import("//ohos_nweb/src/nweb_sysevent.gni")
import("//tools/grit/grit_rule.gni")
import("//tools/grit/repack.gni")

if (defined(is_arkweb_ext) && is_arkweb_ext) {
  import("//arkweb/ohos_nweb_ex/build/features/features.gni")
}

if (is_arkweb) {
  import("//arkweb/build/features/features.gni")
}

component("nweb_hilog") {
  sources = [ "src/nweb_hilog.h" ]

  include_dirs = ohos_src_includes
  deps = [ "//ohos_glue:ohos_adapter_glue_source" ]
}

#################################################

config("cef_nweb_config") {
  include_dirs = [
    "include",
    "src",
    "src/cef_delegate",
    "src/sysevent",
    "//cef",
    "//cef/include",
    "//cef/libcef/browser/net_service",
    "//third_party/skia",
  ]
  include_dirs += ohos_src_includes

  if (defined(arkweb_performance_persistent_task) &&
      arkweb_performance_persistent_task) {
    include_dirs += [
      "browser/performance_manager",
      "browser/performance_manager/mechanisms",
      "browser/performance_manager/policies",
    ]
  }

  defines = [ "USING_CHROMIUM_INCLUDES" ]

  if (product_name == "rk3568") {
    defines += [ "RK3568" ]
  }

  if (defined(report_sys_event) && report_sys_event) {
    defines += [ "REPORT_SYS_EVENT" ]
  }
}

component("cef_nweb") {
  configs += [
    ":cef_nweb_config",
    ":nweb_config",
  ]

  if (use_libfuzzer) {
    configs -= [ "//build/config/gcc:symbol_visibility_hidden" ]
    configs += [ "//build/config/gcc:symbol_visibility_default" ]
    cflags = [ "-DOHOS_FUZZ_COMPILE_ERROR_FIX" ]
  }
  configs += [ "//cef/libcef/features:config" ]

  deps = [
    "//cef/libcef/common/mojom",
    "//cef/libcef/features",
    "//components/js_injection/common",
    "//components/js_injection/common:common_mojom",
    "//ohos_glue:ohos_adapter_glue_source",
    "//third_party:huawei_securec",
  ]

  sources = [
    "src/cef_delegate/nweb_access_request_delegate.cc",
    "src/cef_delegate/nweb_access_request_delegate.h",
    "src/cef_delegate/nweb_accessibility_node_info_impl.cc",
    "src/cef_delegate/nweb_accessibility_node_info_impl.h",
    "src/cef_delegate/nweb_adsblock_manager_delegate.cc",
    "src/cef_delegate/nweb_adsblock_manager_delegate.h",
    "src/cef_delegate/nweb_application.cc",
    "src/cef_delegate/nweb_application.h",
    "src/cef_delegate/nweb_console_log_impl.cc",
    "src/cef_delegate/nweb_console_log_impl.h",
    "src/cef_delegate/nweb_context_menu_params_impl.cc",
    "src/cef_delegate/nweb_context_menu_params_impl.h",
    "src/cef_delegate/nweb_controller_handler_impl.cc",
    "src/cef_delegate/nweb_controller_handler_impl.h",
    "src/cef_delegate/nweb_cookie_impl.cc",
    "src/cef_delegate/nweb_cookie_impl.h",
    "src/cef_delegate/nweb_cookie_manager_delegate.cc",
    "src/cef_delegate/nweb_cookie_manager_delegate.h",
    "src/cef_delegate/nweb_core_value.cc",
    "src/cef_delegate/nweb_core_value.h",
    "src/cef_delegate/nweb_cursor_info_impl.cc",
    "src/cef_delegate/nweb_cursor_info_impl.h",
    "src/cef_delegate/nweb_custom_keyboard_handler_impl.cc",
    "src/cef_delegate/nweb_custom_keyboard_handler_impl.h",
    "src/cef_delegate/nweb_data_base_delegate.cc",
    "src/cef_delegate/nweb_data_base_delegate.h",
    "src/cef_delegate/nweb_data_resubmission_callback_impl.cc",
    "src/cef_delegate/nweb_data_resubmission_callback_impl.h",
    "src/cef_delegate/nweb_date_time_chooser_impl.cc",
    "src/cef_delegate/nweb_date_time_chooser_impl.h",
    "src/cef_delegate/nweb_default_engine_init_args_impl.cc",
    "src/cef_delegate/nweb_default_engine_init_args_impl.h",
    "src/cef_delegate/nweb_default_engine_prefetch_args_impl.cc",
    "src/cef_delegate/nweb_default_engine_prefetch_args_impl.h",
    "src/cef_delegate/nweb_delegate.cc",
    "src/cef_delegate/nweb_delegate.h",
    "src/cef_delegate/nweb_devtools_message_handler_impl.cc",
    "src/cef_delegate/nweb_devtools_message_handler_impl.h",
    "src/cef_delegate/nweb_display_listener.cc",
    "src/cef_delegate/nweb_display_listener.h",
    "src/cef_delegate/nweb_download_handler_delegate.cc",
    "src/cef_delegate/nweb_download_handler_delegate.h",
    "src/cef_delegate/nweb_event_handler.cc",
    "src/cef_delegate/nweb_event_handler.h",
    "src/cef_delegate/nweb_extension_connect_native.cc",
    "src/cef_delegate/nweb_extension_connect_native.h",
    "src/cef_delegate/nweb_file_selector_params_impl.cc",
    "src/cef_delegate/nweb_file_selector_params_impl.h",
    "src/cef_delegate/nweb_find_delegate.cc",
    "src/cef_delegate/nweb_find_delegate.h",
    "src/cef_delegate/nweb_full_screen_exit_handler_impl.cc",
    "src/cef_delegate/nweb_full_screen_exit_handler_impl.h",
    "src/cef_delegate/nweb_geolocation_callback.cc",
    "src/cef_delegate/nweb_geolocation_callback.h",
    "src/cef_delegate/nweb_gesture_event_result_impl.cc",
    "src/cef_delegate/nweb_gesture_event_result_impl.h",
    "src/cef_delegate/nweb_handler_delegate.cc",
    "src/cef_delegate/nweb_handler_delegate.h",
    "src/cef_delegate/nweb_history_list_impl.cc",
    "src/cef_delegate/nweb_history_list_impl.h",
    "src/cef_delegate/nweb_hit_test_result_impl.cc",
    "src/cef_delegate/nweb_hit_test_result_impl.h",
    "src/cef_delegate/nweb_icon_utils.cc",
    "src/cef_delegate/nweb_icon_utils.h",
    "src/cef_delegate/nweb_image_options_impl.cc",
    "src/cef_delegate/nweb_image_options_impl.h",
    "src/cef_delegate/nweb_input_delegate.cc",
    "src/cef_delegate/nweb_input_delegate.h",
    "src/cef_delegate/nweb_inputevent_handler.h",
    "src/cef_delegate/nweb_inputmethod_client.h",
    "src/cef_delegate/nweb_js_dialog_result_impl.cc",
    "src/cef_delegate/nweb_js_dialog_result_impl.h",
    "src/cef_delegate/nweb_js_http_auth_result_impl.cc",
    "src/cef_delegate/nweb_js_http_auth_result_impl.h",
    "src/cef_delegate/nweb_js_ssl_error_result_impl.cc",
    "src/cef_delegate/nweb_js_ssl_error_result_impl.h",
    "src/cef_delegate/nweb_js_ssl_select_cert_result_impl.cc",
    "src/cef_delegate/nweb_js_ssl_select_cert_result_impl.h",
    "src/cef_delegate/nweb_js_verify_pin_result_impl.cc",
    "src/cef_delegate/nweb_js_verify_pin_result_impl.h",
    "src/cef_delegate/nweb_key_event_impl.cc",
    "src/cef_delegate/nweb_key_event_impl.h",
    "src/cef_delegate/nweb_mouse_event_result_impl.cc",
    "src/cef_delegate/nweb_mouse_event_result_impl.h",
    "src/cef_delegate/nweb_preference_delegate.cc",
    "src/cef_delegate/nweb_preference_delegate.h",
    "src/cef_delegate/nweb_render_handler.cc",
    "src/cef_delegate/nweb_render_handler.h",
    "src/cef_delegate/nweb_resource_handler.cc",
    "src/cef_delegate/nweb_resource_handler.h",
    "src/cef_delegate/nweb_select_menu_bound_impl.cc",
    "src/cef_delegate/nweb_select_menu_bound_impl.h",
    "src/cef_delegate/nweb_touch_handle_hot_zone_impl.cc",
    "src/cef_delegate/nweb_touch_handle_hot_zone_impl.h",
    "src/cef_delegate/nweb_touch_handle_state_impl.cc",
    "src/cef_delegate/nweb_touch_handle_state_impl.h",
    "src/cef_delegate/nweb_url_resource_response_impl.cc",
    "src/cef_delegate/nweb_url_resource_response_impl.h",
    "src/cef_delegate/nweb_web_storage_delegate.cc",
    "src/cef_delegate/nweb_web_storage_delegate.h",
    "src/cef_delegate/nweb_web_storage_origin_impl.cc",
    "src/cef_delegate/nweb_web_storage_origin_impl.h",
    "src/sysevent/event_reporter.cc",
    "src/sysevent/event_reporter.h",
    "src/sysevent/oh_web_performance_timing.cc",
    "src/sysevent/oh_web_performance_timing.h",
  ]
  if (defined(arkweb_logger_report) && arkweb_logger_report) {
    sources +=
        [ "//cef/ohos_cef_ext/include/cef_logger_callback_api_handler.h" ]
  }

  if (arkweb_drag_resize) {
    sources += [
      "src/nweb_resize_helper.cc",
      "src/nweb_resize_helper.h",
    ]
  }

  if (defined(arkweb_arkweb_extensions) && arkweb_arkweb_extensions) {
    sources += [
      "src/cef_delegate/nweb_extension_action_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_action_cef_delegate.h",
      "src/cef_delegate/nweb_extension_bookmarks_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_bookmarks_cef_delegate.h",
      "src/cef_delegate/nweb_extension_browsing_data_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_browsing_data_cef_delegate.h",
      "src/cef_delegate/nweb_extension_content_settings_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_content_settings_cef_delegate.h",
      "src/cef_delegate/nweb_extension_downloads_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_downloads_cef_delegate.h",
      "src/cef_delegate/nweb_extension_history_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_history_cef_delegate.h",
      "src/cef_delegate/nweb_extension_omnibox_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_omnibox_cef_delegate.h",
      "src/cef_delegate/nweb_extension_permissions_handler.cc",
      "src/cef_delegate/nweb_extension_permissions_handler.h",
      "src/cef_delegate/nweb_extension_prompt_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_prompt_cef_delegate.h",
      "src/cef_delegate/nweb_extension_proxy_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_proxy_cef_delegate.h",
      "src/cef_delegate/nweb_extension_sessions_handler_delegate.cc",
      "src/cef_delegate/nweb_extension_sessions_handler_delegate.h",
      "src/cef_delegate/nweb_extension_side_panel_cef_controller.cc",
      "src/cef_delegate/nweb_extension_side_panel_cef_controller.h",
      "src/cef_delegate/nweb_extension_side_panel_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_side_panel_cef_delegate.h",
      "src/cef_delegate/nweb_extension_tab_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_tab_cef_delegate.h",
      "src/cef_delegate/nweb_extension_top_sites_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_top_sites_cef_delegate.h",
      "src/cef_delegate/nweb_extension_utils.cc",
      "src/cef_delegate/nweb_extension_utils.h",
      "src/cef_delegate/nweb_extension_window_cef_delegate.cc",
      "src/cef_delegate/nweb_extension_window_cef_delegate.h",
      "src/cef_delegate/nweb_extension_window_delegate_handler.cc",
      "src/cef_delegate/nweb_extension_window_delegate_handler.h",
    ]

    deps += [ "//components/crx_file" ]

    if (defined(arkweb_autolayout) && arkweb_autolayout) {
      sources += [
        "src/cef_delegate/nweb_autolayout.cc",
        "src/cef_delegate/nweb_autolayout.h",
      ]
    }
    if (defined(arkweb_nweb_ex) && arkweb_nweb_ex) {
      deps += [ "//ohos_nweb_ex:dispatcher" ]
    }
  }

  if (defined(arkweb_notification) && arkweb_notification) {
    sources += [
      "src/cef_delegate/nweb_access_query_delegate.cc",
      "src/cef_delegate/nweb_access_query_delegate.h",
      "src/cef_delegate/nweb_permission_query_impl.cc",
    ]
  }

  if (defined(arkweb_scheme_handler) && arkweb_scheme_handler) {
    sources += [
      "src/cef_delegate/nweb_pipe_resource_handler.cc",
      "src/cef_delegate/nweb_pipe_resource_handler.h",
      "src/cef_delegate/nweb_scheme_handler_factory.cc",
      "src/cef_delegate/nweb_scheme_handler_factory.h",
      "src/ndk/scheme_handler/arkweb_scheme_handler.cc",
      "src/ndk/scheme_handler/http_body_stream.cc",
      "src/ndk/scheme_handler/http_body_stream.h",
      "src/ndk/scheme_handler/resource_handler.cc",
      "src/ndk/scheme_handler/resource_handler.h",
      "src/ndk/scheme_handler/resource_request.cc",
      "src/ndk/scheme_handler/resource_request.h",
      "src/ndk/scheme_handler/response.cc",
      "src/ndk/scheme_handler/response.h",
    ]
  }

  sources += [
    "src/ndk/arkweb_model.cc",
    "src/ndk/arkweb_native_javascript_execute_callback.cc",
    "src/ndk/arkweb_native_javascript_execute_callback.h",
    "src/ndk/arkweb_native_object.cc",
    "src/ndk/arkweb_native_object.h",
    "src/ndk/arkweb_native_web_message_callback.cc",
    "src/ndk/arkweb_native_web_message_callback.h",
  ]

  sources += [
    "src/cef_delegate/nweb_value_convert.cc",
    "src/cef_delegate/nweb_value_convert.h",
  ]

  if (defined(arkweb_html_select) && arkweb_html_select) {
    sources += [
      "src/cef_delegate/nweb_select_popup_menu_impl.cc",
      "src/cef_delegate/nweb_select_popup_menu_impl.h",
    ]
  }

  if (defined(arkweb_drag_drop) && arkweb_drag_drop) {
    sources += [
      "src/cef_delegate/nweb_drag_data_impl.cc",
      "src/cef_delegate/nweb_drag_data_impl.h",
    ]
  }

  if (defined(arkweb_performance_persistent_task) &&
      arkweb_performance_persistent_task) {
    sources += [
      "browser/performance_manager/mechanisms/background_task_holder.cc",
      "browser/performance_manager/mechanisms/background_task_holder.h",
      "browser/performance_manager/nweb_performance_manager.cc",
      "browser/performance_manager/nweb_performance_manager.h",
      "browser/performance_manager/policies/background_task_policy.cc",
      "browser/performance_manager/policies/background_task_policy.h",
    ]
  }

  if (defined(arkweb_bfcache) && arkweb_bfcache) {
    sources += [
      "browser/performance_manager/policies/ohos_bfcache_policy.cc",
      "browser/performance_manager/policies/ohos_bfcache_policy.h",
    ]
  }

  #if defined(ARKWEB_CUSTOM_VIDEO_PLAYER)
  if (defined(arkweb_custom_video_player) && arkweb_custom_video_player) {
    sources += [
      "src/cef_delegate/custom_media_player_impl.cc",
      "src/cef_delegate/custom_media_player_impl.h",
      "src/native_media_player/nweb_media_info_impl.cc",
      "src/native_media_player/nweb_media_info_impl.h",
      "src/native_media_player/nweb_native_media_player_handler_impl.cc",
      "src/native_media_player/nweb_native_media_player_handler_impl.h",
    ]
  }

  #endif // ARKWEB_CUSTOM_VIDEO_PLAYER

  deps += [
    "//base:base",
    "//chrome:strings",
    "//content/public/common",
    "//ui/events/keycodes:x11",
  ]
  if (defined(ozone_platform_x11) && ozone_platform_x11) {
    deps += [ "//ui/events/keycodes:x11" ]
  }

  if (defined(arkweb_nweb_ex) && arkweb_nweb_ex) {
    deps += [ "//ohos_nweb_ex/overrides/ohos_nweb" ]
  } else {
    sources += [ "src/cef_delegate/nweb_delegate_ohos.cc" ]
  }

  if (enable_arkweb) {
    deps += [ "//arkweb/build/features" ]
  }

  if (enable_arkweb_ext) {
    deps += [ "//arkweb/ohos_nweb_ex/build/features" ]
  }
}

#################################################

config("nweb_config") {
  defines = [
    "OHOS_NWEB",
    "OS_OHOS",
    "USE_CEF",
  ]

  if (gpu_switch == "off") {
    defines += [ "GPU_RK3568" ]
  }

  include_dirs = [
    "include",
    "src",
  ]

  include_dirs += ohos_src_includes
}

component("nweb_sources") {
  configs += [
    ":nweb_config",
    ":cef_nweb_config",
    "//cef/libcef/features:config",
  ]

  sources = [
    "include/nweb.h",
    "include/nweb_access_request.h",
    "include/nweb_accessibility_event_callback.h",
    "include/nweb_accessibility_node_info.h",
    "include/nweb_console_log.h",
    "include/nweb_controller_handler.h",
    "include/nweb_cookie_manager.h",
    "include/nweb_data_resubmission_callback.h",
    "include/nweb_download_callback.h",
    "include/nweb_download_manager.h",
    "include/nweb_engine.h",
    "include/nweb_find_callback.h",
    "include/nweb_geolocation_callback_interface.h",
    "include/nweb_handler.h",
    "include/nweb_javascript_result_callback.h",
    "include/nweb_js_dialog_result.h",
    "include/nweb_js_http_auth_result.h",
    "include/nweb_key_event.h",
    "include/nweb_preference_delegate.h",
    "include/nweb_value.h",
    "include/nweb_value_callback.h",
    "src/capi/browser_service/nweb_basic_pub.h",
    "src/capi/browser_service/nweb_extension_bookmarks_types.h",
    "src/capi/browser_service/nweb_extension_content_settings_types.h",
    "src/capi/browser_service/nweb_extension_downloads_types.h",
    "src/capi/browser_service/nweb_extension_history_types.h",
    "src/capi/browser_service/nweb_extension_prompt_types.h",
    "src/capi/browser_service/nweb_extension_proxy_types.h",
    "src/capi/nweb_app_client_extension_callback.h",
    "src/capi/nweb_devtools_message_handler.h",
    "src/capi/nweb_extension_javascript_item.h",
    "src/capi/nweb_extension_load_url_params.h",
    "src/capi/nweb_native_embed_first_frame_paint_event.h",
    "src/capi/nweb_statistic_callback.h",
    "src/capi/nweb_storage_extension_callback.h",
    "src/nweb_adsblock_manager_impl.cc",
    "src/nweb_adsblock_manager_impl.h",
    "src/nweb_advanced_security.cc",
    "src/nweb_advanced_security.h",
    "src/nweb_common.cc",
    "src/nweb_common.h",
    "src/nweb_cookie_manager_delegate_interface.h",
    "src/nweb_cookie_manager_impl.cc",
    "src/nweb_cookie_manager_impl.h",
    "src/nweb_data_base_impl.cc",
    "src/nweb_data_base_impl.h",
    "src/nweb_delegate_adapter.cc",
    "src/nweb_delegate_adapter.h",
    "src/nweb_delegate_interface.h",
    "src/nweb_download_manager_impl.cc",
    "src/nweb_download_manager_impl.h",
    "src/nweb_engine_impl.cc",
    "src/nweb_engine_impl.h",
    "src/nweb_first_meaningful_paint_details_impl.cc",
    "src/nweb_first_meaningful_paint_details_impl.h",
    "src/nweb_hilog.h",
    "src/nweb_imf_cursor_info_adapter_impl.cc",
    "src/nweb_imf_cursor_info_adapter_impl.h",
    "src/nweb_imf_input_attribute_adapter_impl.cc",
    "src/nweb_imf_input_attribute_adapter_impl.h",
    "src/nweb_imf_selection_range_adapter_impl.cc",
    "src/nweb_imf_selection_range_adapter_impl.h",
    "src/nweb_imf_text_config_adapter_impl.cc",
    "src/nweb_imf_text_config_adapter_impl.h",
    "src/nweb_impl.cc",
    "src/nweb_impl.h",
    "src/nweb_input_handler.cc",
    "src/nweb_input_handler.h",
    "src/nweb_inputmethod_handler.cc",
    "src/nweb_inputmethod_handler.h",
    "src/nweb_largest_contentful_paint_details_impl.cc",
    "src/nweb_largest_contentful_paint_details_impl.h",
    "src/nweb_output_handler.cc",
    "src/nweb_output_handler.h",
    "src/nweb_runtime_connect_info_impl.cc",
    "src/nweb_runtime_connect_info_impl.h",
    "src/nweb_url_resource_error_impl.hh",
    "src/nweb_url_resource_request_impl.cc",
    "src/nweb_url_resource_request_impl.h",
    "src/nweb_web_storage_impl.cc",
    "src/nweb_web_storage_impl.h",
  ]

  if (defined(arkweb_arkweb_extensions) && arkweb_arkweb_extensions) {
    sources += [
      "src/ohos_nweb/src/capi/nweb_context_menus_item.h",
      "src/ohos_nweb/src/capi/nweb_extension_action_icon.h",
      "src/ohos_nweb/src/capi/nweb_extension_context_menus_callback.h",
    ]
  }

  if (arkweb_navigation) {
    sources += [
      "src/nweb_load_committed_details_impl.cc",
      "src/nweb_load_committed_details_impl.h",
    ]
  }

  if (defined(arkweb_notification) && arkweb_notification) {
    sources += [
      "src/capi/nweb_notification_options_item.h",
      "src/capi/nweb_permission_status_query.h",
      "src/capi/nweb_permission_status_query_delegate_callback.h",
      "src/nweb_access_query.h",
      "src/nweb_notification_manager_delegate.cc",
      "src/nweb_notification_manager_delegate.h",
      "src/nweb_permission_status_query_manager.cc",
      "src/nweb_permission_status_query_manager.h",
    ]
  }

  #endif

  if (!defined(ohos_nweb_ex) || !ohos_nweb_ex) {
    sources += [ "src/download/web_downloader.cc" ]
  }

  if (arkweb_download) {
    sources += [
      "src/nweb_file_writer_cleaner.cc",
      "src/nweb_file_writer_cleaner.h",
    ]
  }

  deps = [
    ":cef_nweb",
    ":nweb_hilog",
    "//arkweb/build/features",
    "//base:base",
    "//cef/libcef/features",
    "//ohos_glue:ohos_nweb_glue_source",
    "//third_party/boringssl",
    "//third_party/icu",
  ]

  if (defined(arkweb_no_state_prefetch) && arkweb_no_state_prefetch) {
    deps += [ "//third_party/boringssl" ]
  }

  public_deps = [ "//third_party/abseil-cpp:absl" ]

  if (enable_arkweb) {
    public_deps += [ "//arkweb/build/features" ]
  }

  if (enable_arkweb_ext) {
    deps += [ "//arkweb/ohos_nweb_ex/build/features" ]
  }

  if (enable_arkweb_ext) {
    public_deps += [ "//arkweb/ohos_nweb_ex/build/features" ]
  }

  deps += [ "//ohos_glue:ohos_adapter_glue_source" ]

  if (defined(arkweb_ai) && arkweb_ai) {
    deps += [ "//ohos_resources/data_detector:data_detector_resources" ]
  }

  if (defined(arkweb_autolayout) && arkweb_autolayout) {
    deps += [ "//arkweb/ohos_autolayout:autolayout_resources" ]
  }

  #if BUILDFLAG(ARKWEB_VIDEO_ASSISTANT)
  if (defined(arkweb_video_assistant) && arkweb_video_assistant) {
    sources += [
      "src/capi/common/common.h",
      "src/capi/nweb_media_player_controller.h",
      "src/capi/nweb_media_player_listener.h",
      "src/cef_delegate/nweb_media_player_for_vast.cc",
      "src/cef_delegate/nweb_media_player_for_vast.h",
      "src/video_assistant/nweb_media_player_controller_impl.cc",
      "src/video_assistant/nweb_media_player_controller_impl.h",
    ]
  }

  #endif ARKWEB_VIDEO_ASSISTANT
}

#################################################

config("ohosnweb_core_config") {
  defines = [
    "OHOS_NWEB",
    "OS_OHOS",
  ]

  include_dirs = [
    "//cef",
    "//cef/include",
    "$root_out_dir/includes/cef",
  ]

  include_dirs += ohos_src_includes
}

action("check_ndk_symbol") {
  script = "//arkweb/ohos_adapter_ndk/ndk_tools/check_ndk.py"

  inputs = [ "//arkweb/ohos_adapter_ndk/ndk_tools/adapter_ndk_api.json" ]

  outputs = [ "$target_out_dir/check_ndk_symbol.stamp" ]

  args = [
    "--input",
    rebase_path(inputs[0], root_build_dir),
  ]

  deps = [ "//cef:libarkweb_engine" ]
}

shared_library("libarkweb_render") {
  configs += [
    "//arkweb/build/config/sanitizers:cfi_config",
    "//cef/libcef/features:config",
  ]
  defines = [ "OHOS_NWEB" ]

  include_dirs = [ "include" ]
  include_dirs += ohos_src_includes

  sources = [
    "src/nweb_render_main.cc",
    "src/set_renderer_seccomp_policy.cc",
  ]

  deps = [
    ":check_ndk_symbol",
    ":nweb_hilog",
    "//base",
    "//cef:libarkweb_engine",
    "//cef:libcef_dll_wrapper",
    "//cef/libcef/features",
    "//sandbox:sandbox",
  ]
}

#################################################

source_set("unittests") {
  testonly = true

  configs += [
    ":nweb_config",
    ":cef_nweb_config",
  ]

  include_dirs = [
    "//ppapi/lib/gl/include",
    "//third_party/webrtc",
  ]

  sources = [
    "browser/performance_manager/mechanisms/background_task_holder_unittest.cc",
    "browser/performance_manager/policies/background_task_policy_unittest.cc",
    "browser/performance_manager/policies/ohos_bfcache_policy_unittest.cc",
    "src/cef_delegate/nweb_access_request_delegate_unittest.cc",
    "src/cef_delegate/nweb_autolayout_unittest.cc",
    "src/cef_delegate/nweb_data_base_delegate_unittes.cc",
    "src/cef_delegate/nweb_delegate_unittest.cc",
    "src/cef_delegate/nweb_event_handler_unittest.cc",
    "src/cef_delegate/nweb_find_delegate_unittest.cc",
    "src/cef_delegate/nweb_handler_delegate_unittest.cc",
    "src/cef_delegate/nweb_pipe_resource_handler_unittest.cc",
    "src/cef_delegate/nweb_preference_delegate_unittest.cc",
    "src/cef_delegate/nweb_render_handler_unittest.cc",
    "src/cef_delegate/nweb_scheme_handler_factory_unittest.cc",
    "src/cef_delegate/nweb_web_storage_delegate_unittest.cc",
    "src/native_media_player/nweb_media_info_impl_unittest.cc",
    "src/native_media_player/nweb_native_media_player_handler_impl_unittests.cc",
    "src/ndk/arkweb_model_unittest.cc",
    "src/ndk/arkweb_native_javascript_execute_callback_unittest.cc",
    "src/ndk/arkweb_native_object_unittest.cc",
    "src/ndk/arkweb_native_web_message_callback_unittest.cc",
    "src/ndk/scheme_handler/arkweb_scheme_handler_unittest.cc",
    "src/ndk/scheme_handler/http_body_stream_unittest.cc",
    "src/ndk/scheme_handler/mock_object.cc",
    "src/ndk/scheme_handler/resource_handler_unittest.cc",
    "src/ndk/scheme_handler/resource_request_unittest.cc",
    "src/ndk/scheme_handler/response_unittest.cc",
    "src/nweb_adsblock_manager_impl_unittest.cc",
    "src/nweb_cookie_manager_impl_unittest.cc",
    "src/nweb_data_base_impl_unittest.cc",
    "src/nweb_download_manager_impl_unittest.cc",
    "src/nweb_engine_impl_unittest.cc",
    "src/nweb_file_writer_cleaner_unittest.cc",
    "src/nweb_impl_unittest.cc",
    "src/nweb_input_handler_unittest.cc",
    "src/nweb_inputmethod_handler_unittest.cc",
    "src/nweb_notification_manager_delegate_unittest.cc",
    "src/nweb_output_handler_unittest.cc",
    "src/nweb_permission_status_query_manager_unittest.cc",
    "src/nweb_resize_helper_unittests.cc",
    "src/nweb_web_storage_impl_unittest.cc",
    "src/set_renderer_seccomp_policy_unittest.cc",
    "src/video_assistant/nweb_media_player_controller_impl_unittest.cc",
  ]

  deps = [
    ":cef_nweb",
    ":nweb_sources",
    "//cef:libcef_static",
    "//components/web_cache/browser:browser",
    "//ohos_glue:ohos_adapter_glue_source",
    "//ohos_glue:ohos_nweb_glue_source",
    "//third_party/boringssl",
    "//third_party/boringssl",
  ]

  if (enable_arkweb) {
    deps += [ "//arkweb/build/features" ]
  }

  if (arkweb_test) {
    deps += [ "//arkweb/ohos_adapter_ndk/mock_ndk_api:mock_base_ohos" ]
  }

  if (enable_arkweb_ext) {
    deps += [ "//arkweb/ohos_nweb_ex/build/features" ]
    sources += [ "//arkweb/ohos_nweb_ex/core/web_screencapturer_unittest.cc" ]
    include_dirs += [
      "//arkweb/ohos_nweb_ex",
      "//arkweb/ohos_nweb/src/capi",
    ]
  }

  public_deps = [
    "//testing/gmock",
    "//third_party/abseil-cpp:absl",
  ]

  if (enable_arkweb) {
    public_deps += [ "//arkweb/build/features" ]
  }

  if (enable_arkweb_ext) {
    public_deps += [ "//arkweb/ohos_nweb_ex/build/features" ]
  }
}
