# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import("//build/config/features.gni")
import("//sandbox/features.gni")
import("//testing/test.gni")

component("arkweb_sandbox") {
  sources = [
    "seccomp-bpf-helpers/baseline_policy_ohos.cc",
    "seccomp-bpf-helpers/baseline_policy_ohos.h",
  ]

  deps = [
    "//base",
  ]
}

component("seccomp_starter_ohos") {
  sources = [
    "seccomp-bpf-helpers/seccomp_starter_ohos.cc",
    "seccomp-bpf-helpers/seccomp_starter_ohos.h",
  ]

  deps = [ "//base" ]

  if (use_seccomp_bpf) {
    deps += [ "//sandbox/linux:seccomp_bpf" ]
  }
}

test("arkweb_sandbox_unittests") {
  include_dirs = [ "//ppapi/lib/gl/include" ]

  sources = [
    "seccomp-bpf-helpers/baseline_policy_ohos_unittest.cc",
    "seccomp-bpf-helpers/seccomp_starter_ohos_unittest.cc"
  ]

  public_deps = [
    "//testing/gmock",
    "//testing/gtest",
  ]

  deps = [
    "//base",
    "//base/test:test_support",
    "//cef:libcef_static",
    "//components/web_cache/browser:browser",
    "//content/public/common",
    "//ohos_glue:ohos_adapter_glue_source",
    "//ohos_glue:ohos_nweb_glue_source",
    "//third_party/boringssl",
  ]

  include_dirs += [ "//third_party/ohos_ndk/includes/ohos_adapter" ]
}
