// Copyright (c) 2024 Huawei Device Co., Ltd. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import { injectable, inject } from 'inversify';
import { BusinessError } from '@ohos.base';
import image from '@ohos.multimedia.image';
import common from '@ohos.app.ability.common';
import { Size } from '@kit.ArkUI';
import { MODULE_TYPE } from "../common/ModuleType";
import { BaseAdapter } from '../common/BaseAdapter';
import LogUtil from '../utils/LogUtil';
import LogMethod from '../common/LogDecorator';

const TAG: string = 'media';

@injectable()
export default class MediaAdapter extends BaseAdapter {
  private previewReceiver: image.ImageReceiver;
  private defaultSize: Size = {
    width: 320,
    height: 240
  };

  constructor(@inject(MODULE_TYPE.Context) ctx: common.UIAbilityContext) {
    super(ctx);
    this.previewReceiver = image.createImageReceiver(this.defaultSize, image.ImageFormat.JPEG, 8);
  }

  @LogMethod
  getPreviewSurfaceId(callback?: Function) {
    this.previewReceiver.getReceivingSurfaceId().then((id:string) => {
      callback && callback(id);
    }).catch((err: BusinessError) => {
      LogUtil.error(TAG, `Failed to get Preview Surface:` + JSON.stringify(err));
    });
  }

  @LogMethod
  getImageReceiver() {
    this.previewReceiver.on('imageArrival', () => {
      let img: image.Image = this.nativeContext.readImageFromReceiver(this.previewReceiver);
      if (img) {
        img.release();
      } else {
        LogUtil.error(TAG, 'image undefined');
      }
    })
  }
}
