# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Extending //components/viz/service:unit_tests target
#

components_viz_service_unittests_ext = {
  sources = [
    "//arkweb/chromium_ext/components/viz/service/display/arkweb_display_utils_unittest.cc",
    "//arkweb/chromium_ext/components/viz/service/display/display_scheduler_utils_unittest.cc",
    "//arkweb/chromium_ext/components/viz/service/display/frame_dump_copy_output_request_unittests.cc",
    "//arkweb/chromium_ext/components/viz/service/gl/gpu_service_impl_utils_unittests.cc",
    "//arkweb/chromium_ext/components/viz/service/frame_sinks/frame_sink_manager_impl_utils_unittests.cc",
    "//arkweb/chromium_ext/components/viz/service/frame_sinks/external_begin_frame_source_ohos_second_unittests.cc",
    "//arkweb/chromium_ext/components/viz/service/frame_sinks/compositor_frame_sink_impl_utils_unittests.cc",
    "//arkweb/chromium_ext/components/viz/service/frame_sinks/root_compositor_frame_sink_impl_ext_unittests.cc",
  ]
  sources_del = [
    "display/display_resource_provider_software_unittest.cc",
    "display/software_renderer_unittest.cc",
    "main/viz_main_impl_unittest.cc",
  ]
  deps = [ "//arkweb/build/features" ]
}
