arkweb_gpu_command_buffer_service_sources = [
    "//arkweb/chromium_ext/gpu/command_buffer/service/abstract_texture_ohos.cc",
    "//arkweb/chromium_ext/gpu/command_buffer/service/abstract_texture_ohos.h",
]

arkweb_gpu_command_buffer_service_unittest = [
    "//arkweb/chromium_ext/gpu/command_buffer/service/abstract_texture_ohos_unittest.cc",
    "//arkweb/chromium_ext/gpu/command_buffer/service/shared_image/service_transfer_cache_ext_unittest.cc",
    "//arkweb/chromium_ext/gpu/ipc/common/gpu_surface_id_tracker_unittest.cc",
    "//arkweb/chromium_ext/gpu/vulkan/ohos/vulkan_implementation_ohos_unittest.cc",
    "//arkweb/chromium_ext/gpu/ipc/service/stream_texture_ohos_unittest2.cc",
    "//arkweb/chromium_ext/gpu/ipc/service/gpu_channel_ext_unittest.cc",
    "//arkweb/chromium_ext/gpu/command_buffer/service/shared_image/gl_texture_ohos_image_representation_unittests.cc",
    "//arkweb/chromium_ext/gpu/command_buffer/service/shared_image/ohos_native_buffer_image_backing_unittests.cc",
]